### ISSUE TITLE
Select PDF - Popup zeigt nur Seiten

### ISSUE THREAD

**Issue by MrMooky** [TildBJ/sz_ebook#5]
Wenn ich eine PDF verknüpfen möchte, erscheint im Popup nur die Übersicht der Seiten und nicht die der Dateien. Übersehe ich hier irgendwas?

![ebook_pdf_auswahl](https://cloud.githubusercontent.com/assets/3603346/8573634/f3e1e096-2592-11e5-9662-94678941e8fa.jpg)

**Comment by blar** [comment]
Es muss zuerst ein eBook in der Listenansicht erstellt werden, das auf die PDF-Datei verweist. Dieses kann dann später im eBook-Plugin unter "Select PDF" ausgewählt werden.

**Comment by TildBJ** [comment]
Falls weiterhin Probleme da sind, gerne wieder öffnen.
